language: php

php:
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - PATH=$PATH:./vendor/bin

cache:
  directories:
    - vendor/

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer checkerror
  - composer checkstyle
  - composer test
